import figma from "@figma/code-connect"

import {Button} from "@qualcomm-ui/react/button"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/ETvFgN3bbNvr6sbpoZyNuA/Base-Component-Library-v1.0.4?node-id=3571-1297",
  {
    example: (props) => {
      return <Button emphasis="neutral">{props.label}</Button>
    },
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("label"),
    },
  },
)
